{{- $apiKey := .Values.apiKey | required ".Values.apiKey is required." -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackstate-k8s-ext.fullname" . }}-secret
  labels:
    {{- include "stackstate-k8s-ext.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ $apiKey | b64enc }}