apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stackstate-openlit-ext.serviceAccountName" . }}
  labels:
    {{- include "stackstate-openlit-ext.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
