{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elemental-lifecycle-manager.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elemental-lifecycle-manager.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: {{ ternary "https" "http" .Values.metrics.secure }}
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "elemental-lifecycle-manager.selectorLabels" . | nindent 4 }}
{{- end }}
