{{- $clusterName := .Values.clusterName | required ".Values.clusterName is required." -}}
{{- $apiKey := .Values.apiKey | required ".Values.apiKey is required." -}}
{{- $otlpHost := .Values.otlpHost | required ".Values.otlpHost is required." -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: open-telemetry-collector
  labels:
    {{- include "suse-observability-otel-collector.labels" . | nindent 4 }}
data:
  CLUSTER_NAME : {{$clusterName | b64enc}}
  API_KEY: {{$apiKey | b64enc}}
  OTLP_HOST: {{$otlpHost | b64enc}}
